"""

Problem :
    How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100
    and 2 ≤ b ≤ 100?

Performance time: ~0.0059s

"""

from timer import timer

timer.start()
print(len(set(a ** b for a in range(2, 101) for b in range(2, 101))))
timer.stop()
